export enum AuthTypes {
  LOGIN = 'LOGIN',
  USER = 'USER',
  PAGINATION = 'PAGINATION'
}

export enum TodosTypes {
  GET_ALL_TODOS = 'GET_ALL_TODOS',
  CREATE_NEW_TODO = 'CREATE_NEW_TODO',
  UPDATE_TODO = 'UPDATE_TODO',
  LOADING_TODOS = 'LOADING_TODOS'
}
